/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitConcernRouteImport } from './routes/submit-concern'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RequestSupportRouteImport } from './routes/request-support'
import { Route as IndexRouteImport } from './routes/index'

const SubmitConcernRoute = SubmitConcernRouteImport.update({
  id: '/submit-concern',
  path: '/submit-concern',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSupportRoute = RequestSupportRouteImport.update({
  id: '/request-support',
  path: '/request-support',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request-support': typeof RequestSupportRoute
  '/resources': typeof ResourcesRoute
  '/submit-concern': typeof SubmitConcernRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request-support': typeof RequestSupportRoute
  '/resources': typeof ResourcesRoute
  '/submit-concern': typeof SubmitConcernRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request-support': typeof RequestSupportRoute
  '/resources': typeof ResourcesRoute
  '/submit-concern': typeof SubmitConcernRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/request-support' | '/resources' | '/submit-concern'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/request-support' | '/resources' | '/submit-concern'
  id: '__root__' | '/' | '/request-support' | '/resources' | '/submit-concern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestSupportRoute: typeof RequestSupportRoute
  ResourcesRoute: typeof ResourcesRoute
  SubmitConcernRoute: typeof SubmitConcernRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-concern': {
      id: '/submit-concern'
      path: '/submit-concern'
      fullPath: '/submit-concern'
      preLoaderRoute: typeof SubmitConcernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-support': {
      id: '/request-support'
      path: '/request-support'
      fullPath: '/request-support'
      preLoaderRoute: typeof RequestSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestSupportRoute: RequestSupportRoute,
  ResourcesRoute: ResourcesRoute,
  SubmitConcernRoute: SubmitConcernRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
